#!/usr/bin/env bash
#
# NAME:
#   info - show all info files from temporary folder
#
# SYNOPSIS:
#   info
#
# DESCRIPTION:
# - Script displays content of all files with extension '.inf' in the folder '/tmp'.
#
# LICENSE:
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
cat /tmp/*.inf
